apiVersion: v1
kind: Service
metadata:
  name: caddy-checker
  namespace: apps
  labels:
    app: caddy-checker
spec:
  selector:
    app: caddy-checker
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
