apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caddy-checker
  namespace: apps
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: caddy-checker
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
