apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caddy-checker
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: caddy-checker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
