apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caddy-blackbox
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /probe
      interval: 15s
      params:
        module:
          - http_2xx
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
          replacement: http://caddy.apps.svc.cluster.local
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: blackbox-exporter.monitoring.svc.cluster.local:9115
