apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.51.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path

    # ✅ Disable Helm tests (chart complains if canary is disabled)
    test:
      enabled: false

    # Small lab mode: disable caches/canary/gateway
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    gateway:
      enabled: false

    # Disable distributed pieces for a small lab
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
