apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: apps
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 2019
      targetPort: 2019
